on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: ./.github/actions/ksqldb-migrations-validate
      - uses: ./.github/actions/ksqldb-migrations-apply
